sudo: false
language: node_js
node_js: node
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: hzbSCcVqYRmBGs+vpAyVopppfu8cwnMwHF+bhHFNCmLU/GVq9ZmAjP/xeIk5PCiiox/qqvIHjSg51FZYmKAgji+W4dCVpTUm2O0SIUGm4ZBJQis6BzOBWWU/bKbsjvxYNsVZMAjy1MHl3r5rysLNMW70lrhs6oTBOANkBLo3ok0=
  on:
    tags: true
    repo: bitovi/testee-client
